package org.example.venta;// Generated by Selenium IDE
import org.example.login.Login;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class IntoVentaPruebaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void intoVentaPrueba() {
    driver = Login.login();
    driver.findElement(By.id("popup_ok")).click();
    driver.findElement(By.cssSelector(".openSidebar")).click();
    driver.findElement(By.linkText("Ventas")).click();
    driver.findElement(By.cssSelector(".mod-1:nth-child(3) a")).click();

    String expectedTitle = "Ventas";
    String actualTitle = driver.getTitle();
    Assert.assertEquals(expectedTitle, actualTitle);
  }
  @Test
  public void testCotizacionesModule() {
    driver = Login.login();
    driver.findElement(By.id("popup_ok")).click();
    driver.findElement(By.cssSelector(".openSidebar")).click();
    driver.findElement(By.linkText("Ventas")).click();
    driver.findElement(By.cssSelector(".mod-1:nth-child(5) a")).click();
    // Add assertions or further actions related to the Cotizaciones module
    String expectedTitle = "Cotizaciones";
    String actualTitle = driver.getTitle();
    Assert.assertEquals(expectedTitle, actualTitle);
  }
  @Test
  public void testDevolucionesModule() {
    driver = Login.login();
    driver.findElement(By.id("popup_ok")).click();
    driver.findElement(By.cssSelector(".openSidebar")).click();
    driver.findElement(By.linkText("Ventas")).click();
    driver.findElement(By.cssSelector(".mod-1:nth-child(8) a")).click();
    // Add assertions or further actions related to the Cotizaciones module
    String expectedTitle = "Devoluciones";
    String actualTitle = driver.getTitle();
    Assert.assertEquals(expectedTitle, actualTitle);
  }

  @Test
  public void testSeparadosModule() {
    driver = Login.login();
    driver.findElement(By.id("popup_ok")).click();
    driver.findElement(By.cssSelector(".openSidebar")).click();
    driver.findElement(By.linkText("Ventas")).click();
    driver.findElement(By.cssSelector(".mod-1:nth-child(10) a")).click();
    // Add assertions or further actions related to the Cotizaciones module
    String expectedTitle = "Separados";
    String actualTitle = driver.getTitle();
    Assert.assertEquals(expectedTitle, actualTitle);
  }

  @Test
  public void testRemisionesModule() {
    driver = Login.login();
    driver.findElement(By.id("popup_ok")).click();
    driver.findElement(By.cssSelector(".openSidebar")).click();
    driver.findElement(By.linkText("Ventas")).click();
    driver.findElement(By.cssSelector(".mod-1:nth-child(12) a")).click();
    // Add assertions or further actions related to the Cotizaciones module
    String expectedTitle = "Remisiones";
    String actualTitle = driver.getTitle();
    Assert.assertEquals(expectedTitle, actualTitle);
  }

  @Test
  public void testRemisionesAtrasadasModule() {
    driver = Login.login();
    driver.findElement(By.id("popup_ok")).click();
    driver.findElement(By.cssSelector(".openSidebar")).click();
    driver.findElement(By.linkText("Ventas")).click();
    driver.findElement(By.cssSelector(".mod-1:nth-child(13) a")).click();
    // Add assertions or further actions related to the Cotizaciones module
    String expectedTitle = "Lista Remisiones Clientes Atrasados";
    String actualTitle = driver.getTitle();
    Assert.assertEquals(expectedTitle, actualTitle);
  }


}
